version: "3.8"
services:
  server:
    image: judge0
    command: [ "cd /api; /api/scripts/server" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "3000:2358"
    privileged: true
    restart: always
    depends_on:
      - db
      - redis


  worker:
    image: judge0
    command: [ "cd /api; /api/scripts/workers" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - ./judge0_data/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - ./judge0_data/redis-data:/data
    restart: always
    depends_on:
      - db
